[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
invariant_task = "EMjE3UTNgvN79M5utukj1Q6UJqpFYinF7AxCV1oAY3gZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/niferu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
